const likes = [
    "life elixir",
    "maple syrup",
    "pina colada",
    "rainbow shell",
    "treasure chest",
    "honey",
    "wine",
    "pale ale",
    "beer",
    "mead",
    "cheese",
    "goat cheese",
    "vinegar",
    "coffee",
    "green tea",
    "juice",
    "cloth",
    "mayonnaise",
    "duck mayonnaise",
    "dinosaur mayonnaise",
    "truffle oil",
    "pickles",
    "jelly",
    "caviar",
    "aged roe",
    "dried mushrooms",
    "dried fruit",
    "raisins",
    "smoked fish",
    "maple syrup",
    "oak resin",
    "pine tar",
    "mystic syrup",
    "omelet",
    "salad",
    "cheese cauliflower",
    "baked fish",
    "parsnip soup",
    "vegetable medley",
    "complete breakfast",
    "fried calamari",
    "lucky lunch",
    "fried mushroom",
    "pizza",
    "bean hotpot",
    "glazed yams",
    "carp surprise",
    "hashbrowns",
    "pancakes",
    "salmon dinner",
    "fish taco",
    "crispy bass",
    "pepper poppers",
    "tom kha soup",
    "trout soup",
    "chocolate cake",
    "pink cake",
    "rhubarb pie",
    "cookie",
    "spaghetti",
    "fried eel",
    "spicy eel",
    "sashimi",
    "maki roll",
    "tortilla",
    "red plate",
    "egglplant parmesan",
    "rice pudding",
    "ice cream",
    "blueberry tart",
    "autumn's bounty",
    "pumpkin soup",
    "super meal",
    "cranberry sauce",
    "stuffing",
    "farmer's lunch",
    "survivial burger",
    "dish o' the sea",
    "miner's treat",
    "roots platter",
    "triple shot espresso",
    "algae soup",
    "pale broth",
    "plum pudding",
    "artichoke dip",
    "stir fry",
    "roasted hazelnuts",
    "pumpkin pie",
    "radish salad",
    "fruit salad",
    "blackberry cobbler",
    "cranberry candy",
    "bruschetta",
    "coleslaw",
    "fiddlehead risotto",
    "poppyseed muffin",
    "chowder",
    "fish stew",
    "escargot",
    "lobster bisque",
    "maple bar",
    "crab cakes",
    "shrimp cocktail",
    "ginger ale",
    "banana pudding",
    "mango sticky rice",
    "poi",
    "tropical curry",
    "squid ink ravioli",
    "moss soup",
    "sweet pea",
    "crocus",
    "tulip",
    "blue jazz",
    "summer spangle",
    "sunflower",
    "fairy rose",
    "earth crystal",
    "frozen tear",
    "fire quartz",
    "apple",
    "apricot",
    "banana",
    "cherry",
    "mango",
    "orange",
    "peach",
    "pomegranate",
    "emerald",
    "aquamarine",
    "ruby",
    "amethyst",
    "topaz",
    "jade",
    "diamond",
    "amaranth",
    "artichoke",
    "beet",
    "bok choy",
    "broccoli",
    "carrot",
    "cauliflower",
    "corn",
    "eggplant",
    "fiddlehead fern",
    "garlic",
    "green bean",
    "kale",
    "parsnip",
    "potato",
    "pumpkin",
    "radish",
    "red cabbage",
    "summer squash",
    "taro root",
    "tomato",
    "yam"

]

module.expoorts = likes