const neutral = [
    "bread",
    "coral",
    "duck feather",
    "fried egg",
    "hops",
    "mystic syrup",
    "nautilus shell",
    "roe",
    "squid ink",
    "sweet gem berry",
    "tea leaves",
    "truffle",
    "wheat",
    "wool",
    "price catalogue",
    "mapping cave systems",
    "way of the wind pt. 1",
    "way of the wind pt. 2",
    "monster compendium",
    "friendship 101",
    "jack be nimble, jack be thick",
    "woody's secret",
    "raccoon journal",
    "jewels of the sea",
    "dwarvish safety manual",
    "the art o' crabbing",
    "the alleyway buffet",
    "the diamond hunter",
    "book of mysteries",
    "horse: the book",
    "treasure appraisal guide",
    "ol' slitherlegs",
    "animal catalogue",
    "bait and bobber",
    "book of stars",
    "combat quarterly",
    "mining monthly",
    "queen of sauce cookbook",
    "stardew valley almanac",
    "woodcutter's weekly"
]

module.expoorts = neutral